/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

/**
 *
 * @author Juan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBacosi = new javax.swing.JPanel();
        jLabelUsuarioBacosi = new javax.swing.JLabel();
        jTextFieldUsuarioBacosi = new javax.swing.JTextField();
        jLabelClaveBacosi = new javax.swing.JLabel();
        jTextFieldClaveBacosi = new javax.swing.JTextField();
        jLabelIpBacosi = new javax.swing.JLabel();
        jTextFieldIpBacosi = new javax.swing.JTextField();
        jLabelBdBacosi = new javax.swing.JLabel();
        jTextFieldBdBacosi = new javax.swing.JTextField();
        jLabelInstancia = new javax.swing.JLabel();
        jTextFieldInstancia = new javax.swing.JTextField();
        jLabelPuertoBacosi = new javax.swing.JLabel();
        jTextFieldPuertoBacosi = new javax.swing.JTextField();
        jPanelAs400 = new javax.swing.JPanel();
        jLabelUsuarioAs400 = new javax.swing.JLabel();
        jTextFieldUsuarioAs400 = new javax.swing.JTextField();
        jLabelClaveAs400 = new javax.swing.JLabel();
        jTextFieldClaveAs400 = new javax.swing.JTextField();
        jLabelIpAs400 = new javax.swing.JLabel();
        jTextFieldIpAs400 = new javax.swing.JTextField();
        jLabelLibAs400Programa = new javax.swing.JLabel();
        jTextFieldLibAs400Programa = new javax.swing.JTextField();
        jLabelLibAs400Archivos = new javax.swing.JLabel();
        jTextFieldLibAs400Archivos = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obtener Usuarios Domiciliaciones");

        jPanelBacosi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Servidor Bacosi", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabelUsuarioBacosi.setText("Usuario:");

        jLabelClaveBacosi.setText("Clave:");

        jLabelIpBacosi.setText("IP:");

        jLabelBdBacosi.setText("Base de Datos:");

        jLabelInstancia.setText("Instancia:");

        jLabelPuertoBacosi.setText("Puerto:");

        javax.swing.GroupLayout jPanelBacosiLayout = new javax.swing.GroupLayout(jPanelBacosi);
        jPanelBacosi.setLayout(jPanelBacosiLayout);
        jPanelBacosiLayout.setHorizontalGroup(
            jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBacosiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIpBacosi)
                    .addComponent(jLabelClaveBacosi)
                    .addComponent(jLabelUsuarioBacosi)
                    .addComponent(jLabelBdBacosi)
                    .addComponent(jLabelPuertoBacosi)
                    .addComponent(jLabelInstancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBacosiLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBacosiLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUsuarioBacosi)
                                    .addComponent(jTextFieldClaveBacosi)
                                    .addComponent(jTextFieldIpBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldBdBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldPuertoBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanelBacosiLayout.setVerticalGroup(
            jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBacosiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuarioBacosi)
                    .addComponent(jTextFieldUsuarioBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClaveBacosi)
                    .addComponent(jTextFieldClaveBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIpBacosi)
                    .addComponent(jTextFieldIpBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBdBacosi)
                    .addComponent(jTextFieldBdBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPuertoBacosi)
                    .addComponent(jTextFieldPuertoBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBacosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInstancia)
                    .addComponent(jTextFieldInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAs400.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Servidor AS 400"));

        jLabelUsuarioAs400.setText("Usuario:");

        jLabelClaveAs400.setText("Clave:");

        jLabelIpAs400.setText("IP:");

        jLabelLibAs400Programa.setText("Libreria Programas:");

        jLabelLibAs400Archivos.setText("Libreria Archivos:");

        javax.swing.GroupLayout jPanelAs400Layout = new javax.swing.GroupLayout(jPanelAs400);
        jPanelAs400.setLayout(jPanelAs400Layout);
        jPanelAs400Layout.setHorizontalGroup(
            jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAs400Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLibAs400Programa)
                    .addComponent(jLabelIpAs400)
                    .addComponent(jLabelClaveAs400)
                    .addComponent(jLabelUsuarioAs400)
                    .addComponent(jLabelLibAs400Archivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldUsuarioAs400)
                        .addComponent(jTextFieldClaveAs400)
                        .addComponent(jTextFieldIpAs400, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldLibAs400Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLibAs400Programa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanelAs400Layout.setVerticalGroup(
            jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAs400Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuarioAs400)
                    .addComponent(jTextFieldUsuarioAs400, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClaveAs400)
                    .addComponent(jTextFieldClaveAs400, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIpAs400)
                    .addComponent(jTextFieldIpAs400, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLibAs400Programa)
                    .addComponent(jTextFieldLibAs400Programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAs400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLibAs400Archivos)
                    .addComponent(jTextFieldLibAs400Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelAs400, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnProcesar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBacosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAs400, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnProcesar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabelBdBacosi;
    private javax.swing.JLabel jLabelClaveAs400;
    private javax.swing.JLabel jLabelClaveBacosi;
    private javax.swing.JLabel jLabelInstancia;
    private javax.swing.JLabel jLabelIpAs400;
    private javax.swing.JLabel jLabelIpBacosi;
    private javax.swing.JLabel jLabelLibAs400Archivos;
    private javax.swing.JLabel jLabelLibAs400Programa;
    private javax.swing.JLabel jLabelPuertoBacosi;
    private javax.swing.JLabel jLabelUsuarioAs400;
    private javax.swing.JLabel jLabelUsuarioBacosi;
    private javax.swing.JPanel jPanelAs400;
    private javax.swing.JPanel jPanelBacosi;
    private javax.swing.JTextField jTextFieldBdBacosi;
    private javax.swing.JTextField jTextFieldClaveAs400;
    private javax.swing.JTextField jTextFieldClaveBacosi;
    private javax.swing.JTextField jTextFieldInstancia;
    private javax.swing.JTextField jTextFieldIpAs400;
    private javax.swing.JTextField jTextFieldIpBacosi;
    private javax.swing.JTextField jTextFieldLibAs400Archivos;
    private javax.swing.JTextField jTextFieldLibAs400Programa;
    private javax.swing.JTextField jTextFieldPuertoBacosi;
    private javax.swing.JTextField jTextFieldUsuarioAs400;
    private javax.swing.JTextField jTextFieldUsuarioBacosi;
    // End of variables declaration//GEN-END:variables
}
